# For more information: https://laravel.com/docs/sail
services:
  comic-app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: comic-app
    container_name: comic-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${WEB_APP_PORT:-8000}:80"
    expose:
      - "9003"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
    networks:
      - comic-app
    depends_on:
      - mysql
      - redis
  mysql:
    image: "mysql:8.0.35"
    container_name: comic-app-mysql8
    platform: linux/x86_64
    ports:
      - "${FORWARD_DB_PORT:-3307}:3306"
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "comic-app-mysql:/var/lib/mysql"
    networks:
      - comic-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    volumes:
      - "comic-app-redis:/data"
    networks:
      - comic-app
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: comic-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOSTS: mysql
      PMA_PORTS: 3306
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3080:80
    networks:
      - comic-app
    healthcheck:
      test: ["CMD", "curl", "-Ss", "http://localhost/robots.txt"]
      timeout: 10s
      retries: 3
  mailhog:
    image: axllent/mailpit
    logging:
      driver: "none" # disable saving logs
    expose:
      - 1025 # internal SMTP port
    ports:
      - "8025:8025"
    restart: on-failure
    networks:
      - comic-app
networks:
  comic-app:
    driver: bridge
volumes:
  comic-app-redis:
    driver: local
  comic-app-mysql:
    driver: local
